Small adjustments to the README
hashue/gh-fuzzyclone pull request #9
Opened 2023-03-15 01:25 UTC by waldyrious

- Link to ghq, break its line and add missing punctuation; 
- Tweak wording in Requirements section for consistency;
- Clarify that the username is passed as the second parameter.

2023-03-15 12:09 UTC, hashue commented on README.md
> +To get other repositories, you can pass in a username as a second parameter, like so:
It is not always username as second parameter.

2023-03-15 12:10 UTC, hashue requested changes

2023-03-15 12:10 UTC, hashue commented on README.md
> +To get other repositories, you can pass in a username as a second parameter, like so:
It is not always username as second parameter.

2023-03-15 12:10 UTC, hashue commented on README.md
> +If you want to use [`ghq`](https://github.com/x-motemen/ghq),
I think unnecessary ghq link 'cuase not use ghq in my plugins

2023-03-16 10:08 UTC, waldyrious commented on README.md
> +To get other repositories, you can pass in a username as a second parameter, like so:
Oh, interesting. Can you help clarify with an example or two where that's not the case?

2023-03-16 10:10 UTC, waldyrious commented on README.md
> +If you want to use [`ghq`](https://github.com/x-motemen/ghq),
It's just so people will know what you mean when you refer to ghq. The link itself only provides information if someone happens to not be familiar with ghq when they come across this repo and read the README (that was my case, for example). Those who already know what ghq is can simply ignore the link, so as I see it, there's no harm in adding it.

2023-03-19 11:35 UTC, hashue commented on README.md
> +To get other repositories, you can pass in a username as a second parameter, like so:
@waldyrious Sorry for late response.

Please check this PR.
https://github.com/hashue/gh-fuzzyclone/pull/1

2023-03-19 12:56 UTC, waldyrious commented on README.md
> +To get other repositories, you can pass in a username as a second parameter, like so:
I think I see what you mean. How about this, then?

> To get other repositories, you can pass in a username as an additional parameter, like so:
> ```
> gh fuzzyclone <username> <repository>
> ```

2023-03-19 13:22 UTC, hashue commented on README.md
> +To get other repositories, you can pass in a username as a second parameter, like so:
Sounds great！！！
I'll merge this change applied！

2023-03-19 18:55 UTC, waldyrious commented on README.md
> +To get other repositories, you can pass in a username as a second parameter, like so:
Cool! I've applied the change :)

2023-03-19 21:20 UTC, merged

2023-03-19 21:21 UTC, hashue commented
@waldyrious Cool！I merged.